address/urls.py
from django.urls import  path
from . import views

urlpatterns = [
    path('', views.AddressListView.as_view(), name='home'),
    path('add/', views.AddressCreateView.as_view(), name='address_add'),
    path('ajax/load-states/', views.load_states, name='ajax_load_states'),
    path('ajax/load-districts/', views.load_districts, name='ajax_load_districts'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),
   ]

ohlocal/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('address/', include('address.urls')),
]

address/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=30)
 
    def __str__(self):
        return self.name

class State(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name
class District(models.Model):
    district = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name
class City(models.Model):
    city = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Address(models.Model):
   
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)

address/forms.py
from django import forms
from .models import State, Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('country', 'state', 'district','city')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['state'].queryset = State.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['state'].queryset = State.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass  
        elif self.instance.pk:
            self.fields['state'].queryset = self.instance.country.state_set.order_by('name')

address/views.py
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from .models import Address, City, District,State
from .forms import AddressForm
from django.shortcuts import render

class AddressCreateView(CreateView):
    model = Address
    form_class = AddressForm
    success_url = reverse_lazy('home')

class AddressListView(ListView):
    model = Address
    form_class = AddressForm
    context_object_name = 'addresses'

def load_states(request):
    country_id = request.GET.get('country')
    states = State.objects.filter(country_id=country_id).order_by('name')
    return render(request, 'address/state_dropdown_list_options.html', {'states': states})

def load_districts(request):
    district_id = request.GET.get('state')
    districts = District.objects.filter(district_id=district_id).order_by('name')
    return render(request, 'address/district_dropdown_list_options.html', {'districts': districts})
def load_cities(request):
    city_id = request.GET.get('district')
    cities = City.objects.filter(city_id=city_id).order_by('name')
    return render(request, 'address/city_dropdown_list_options.html', {'cities': cities})

address/templates/address/address_form.html
{% extends 'base.html' %}

{% block content %}

  <h2>Address Form</h2>
  <form method="post" id="addressForm" 
  data-states-url="{% url 'ajax_load_states' %}" 
  data-districts-url="{% url 'ajax_load_districts' %}" 
  data-cities-url="{% url 'ajax_load_cities' %}" 
  novalidate>
    {% csrf_token %}
    <table>
      
      {{ form.as_table }}
    </table>
    <button type="submit">Save</button>
  </form>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<script>
  
  // fetch states
    $("#id_country").change(function () {
      console.log("States");
      var url = $("#addressForm").attr("data-states-url");  
      var countryId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'country': countryId       
        },
        success: function (data) {  
          $("#id_state").html(data);  
        }
      });

    });
  
    // fetch districts
    $("#id_state").change(function () {
      console.log("District");
      var url = $("#addressForm").attr("data-districts-url");  
      var stateId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'state': stateId       
        },
        success: function (data) {  
          $("#id_district").html(data);  
        }
      });

    });

    // fetch cities
     $("#id_district").change(function () {
      var url = $("#addressForm").attr("data-cities-url");  
      var districtId = $(this).val();  

      $.ajax({                      
        url: url,                    
        data: {
          'district': districtId       
        },
        success: function (data) {  
          $("#id_city").html(data);  
        }
      });

    }); 
  </script>


{% endblock %}

address/templates/address/address_list.html
{% extends 'base.html' %}

{% block title %}Addresses{% endblock %}

{% block content %}
  <h2>Address list</h2>

  <p>
    <a href="{% url 'address_add' %}">Add Address</a>
  </p>

  <table border="1" >
    <thead>
      <tr>
        <th>Country</th>
        <th>State</th>
        <th>District</th>
        <th>City</th>
      </tr>
    </thead>
    <tbody>
      {% for add in addresses %}
        <tr>
          <td>{{ add.country }}</td>
          <td>{{ add.state }}</td>
          <td>{{ add.district }}</td>
          <td>{{ add.city }}</td>
          
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">No Address in the database. <a href="{% url 'address_add' %}">Add the first Address</a>.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

address/templates/address/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

address/templates/address/district_dropdown_list_options.html
<option value="">---------</option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}

address/templates/address/state_dropdown_list_options.html
<option value="">---------</option>
{% for state in states %}
<option value="{{ state.pk }}">{{ state.name }}</option>
{% endfor %}

templates/base.html
{% load static %}
<!doctype html>
<meta charset="utf-8">
    <title>{% block title %}Address Database{% endblock %}</title>
    <style type="text/css">
      .errorlist {
        margin: 0;
        padding: 0;
      }
      .errorlist li {
        list-style: none;
        font-size: 90%;
        color: red;
      }
      .errorlist ~ input,
      .errorlist ~ select {
        border-color: red;
      }
    </style>
  <head>
    
  </head>
  <body>
    <h1>Address Database</h1>
    <hr>

    {% block content %}
    {% endblock %}
  </body>
</html>